name: Node 12
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: awharn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            IMAGE_VERSION_ARG=12
          tags: |
            awharn/jenkins-nvm-agent:latest
            awharn/jenkins-nvm-agent:12
            ghcr.io/awharn/jenkins-nvm-agent:latest
            ghcr.io/awharn/jenkins-nvm-agent:12
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}
      
      - name: Update Downstream
        uses: benc-uk/workflow-dispatch@v1
        with: 
          workflow: latest-v12
          repo:     awharn/jenkins-nvm-keytar
          token:    ${{ secrets.PAT }}